name: Deployment Pipeline1
on: push
jobs:
  runs-on: ubuntu latest
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: install Dependencies
      run: npm ci
    - name: run Lint
      run: npm run lint
    - name: Build
      run: npm run build
    - name: Deployment
      run: echo "Deployment Done"