name: Deployment Pipeline1
on: 
  push:
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./04 Practice Project (Start)

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install Dependencies
        run: npm ci
      - name: run Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Deployment
        run: echo "Deployment Done"